version: 2

project_name: websiteSimilar

before:
  hooks:
    - go mod download
    
builds:
- env:
    - CGO_ENABLED=0
    # Only obfuscate this module's packages; do NOT obfuscate stdlib/runtime internals.
    - GOGARBLE=github.com/0cat/websiteSimilar/...
    - GARBLE_LINK_TINY=true
    - GARBLE_SEED=random
  goos:
    - windows
    - linux
    - darwin
    - freebsd
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  ignore:
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
    - goos: freebsd
      goarch: arm

  gobinary: "garble"
  ldflags: "-s -w"
  flags: "-a -trimpath"
  binary: '{{ .ProjectName }}'
  main: ./cmd/main.go

archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  algorithm: sha256